x=int(input("informe um valor "))
y=int(input("informe um segundo valor "))
z=int(input("informe um terceiro valor "))
r=(x**2)+(y**2)+(z**2)
print("o resultado da soma do quadrado dos valor informado é ",r)